#parameters.yml
apiname: <api-name>
stage: <stage>
accountid: <aws-accountid>
vpc: <vpc-id>
subnet1: <subnet1-id>
subnet2: <subnet2-id>
elbsubnet1: <alb-subnet1-id>
elbsubnet2: <alb-subnet2-id>
sg: <sg-id>
elbsg: <alb-sg-id>
region: <aws-region>
repouri: <default-image-uri>
cftemplate: <s3-url-for-cloudformation-template>
